language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test:ci
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
